// {
//   dir: '/Volumes/safari/flow/keats/keatsAmpLite/project-keats-amp-lite',
//   dev: false,
//   isServer: true,
//   buildId: 'keats-lite-build-id',
//   config: {
//     env: [],
//     webpack: [Function: webpack],
//     webpackDevMiddleware: null,
//     distDir: '.next',
//     assetPrefix: './',
//     configOrigin: 'next.config.js',
//     useFileSystemPublicRoutes: true,
//     generateBuildId: [AsyncFunction: generateBuildId],
//     generateEtags: false,
//     pageExtensions: [ 'tsx', 'ts', 'jsx', 'js' ],
//     target: 'server',
//     poweredByHeader: true,
//     compress: true,
//     analyticsId: '',
//     images: {
//       deviceSizes: [Array],
//       imageSizes: [Array],
//       path: '/_next/image',
//       loader: 'default',
//       domains: [],
//       enableBlurryPlaceholder: false
//     },
//     devIndicators: { buildActivity: true },
//     onDemandEntries: { maxInactiveAge: 60000, pagesBufferLength: 2 },
//     amp: { canonicalBase: '' },
//     basePath: '',
//     sassOptions: {},
//     trailingSlash: false,
//     i18n: null,
//     productionBrowserSourceMaps: false,
//     optimizeFonts: true,
//     experimental: {
//       cpus: 15,
//       plugins: false,
//       profiling: false,
//       sprFlushToDisk: true,
//       workerThreads: false,
//       pageEnv: false,
//       optimizeImages: false,
//       optimizeCss: false,
//       scrollRestoration: false,
//       scriptLoader: false,
//       stats: false,
//       externalDir: false,
//       serialWebpackBuild: false,
//       turboMode: false,
//       eslint: false,
//       reactRoot: false,
//       enableBlurryPlaceholder: false,
//       disableOptimizedLoading: true,
//       gzipSize: true
//     },
//     future: {
//       strictPostcssConfiguration: false,
//       excludeDefaultMomentLocales: false,
//       webpack5: false
//     },
//     serverRuntimeConfig: {},
//     publicRuntimeConfig: {},
//     reactStrictMode: false,
//     configFile: '/Volumes/safari/flow/keats/keatsAmpLite/project-keats-amp-lite/next.config.js'
//   },
//   defaultLoaders: {
//     babel: { loader: 'next-babel-loader', options: [Object] },
//     hotSelfAccept: { loader: 'noop-loader' }
//   },
//   totalPages: 6,
//   webpack: [Function: webpack] {
//     version: '4.44.1',
//     WebpackOptionsDefaulter: [class WebpackOptionsDefaulter extends OptionsDefaulter],
//     WebpackOptionsApply: [class WebpackOptionsApply extends OptionsApply],
//     Compiler: [class Compiler extends Tapable],
//     MultiCompiler: [class MultiCompiler extends Tapable],
//     NodeEnvironmentPlugin: [class NodeEnvironmentPlugin],
//     validate: [Function: bound validateSchema],
//     validateSchema: [Function: validateSchema],
//     WebpackOptionsValidationError: [class WebpackOptionsValidationError extends WebpackError],
//     AutomaticPrefetchPlugin: [Getter],
//     BannerPlugin: [Getter],
//     CachePlugin: [Getter],
//     ContextExclusionPlugin: [Getter],
//     ContextReplacementPlugin: [Getter],
//     DefinePlugin: [Getter],
//     Dependency: [Getter],
//     DllPlugin: [Getter],
//     DllReferencePlugin: [Getter],
//     EnvironmentPlugin: [Getter],
//     EvalDevToolModulePlugin: [Getter],
//     EvalSourceMapDevToolPlugin: [Getter],
//     ExtendedAPIPlugin: [Getter],
//     ExternalsPlugin: [Getter],
//     HashedModuleIdsPlugin: [Getter],
//     HotModuleReplacementPlugin: [Getter],
//     IgnorePlugin: [Getter],
//     LibraryTemplatePlugin: [Getter],
//     LoaderOptionsPlugin: [Getter],
//     LoaderTargetPlugin: [Getter],
//     MemoryOutputFileSystem: [Getter],
//     Module: [Getter],
//     ModuleFilenameHelpers: [Getter],
//     NamedChunksPlugin: [Getter],
//     NamedModulesPlugin: [Getter],
//     NoEmitOnErrorsPlugin: [Getter],
//     NormalModuleReplacementPlugin: [Getter],
//     PrefetchPlugin: [Getter],
//     ProgressPlugin: [Getter],
//     ProvidePlugin: [Getter],
//     SetVarMainTemplatePlugin: [Getter],
//     SingleEntryPlugin: [Getter],
//     SourceMapDevToolPlugin: [Getter],
//     Stats: [Getter],
//     Template: [Getter],
//     UmdMainTemplatePlugin: [Getter],
//     WatchIgnorePlugin: [Getter],
//     dependencies: { DependencyReference: [Getter] },
//     optimize: {
//       AggressiveMergingPlugin: [Getter],
//       AggressiveSplittingPlugin: [Getter],
//       ChunkModuleIdRangePlugin: [Getter],
//       LimitChunkCountPlugin: [Getter],
//       MinChunkSizePlugin: [Getter],
//       ModuleConcatenationPlugin: [Getter],
//       OccurrenceOrderPlugin: [Getter],
//       OccurrenceModuleOrderPlugin: [Getter],
//       OccurrenceChunkOrderPlugin: [Getter],
//       RuntimeChunkPlugin: [Getter],
//       SideEffectsFlagPlugin: [Getter],
//       SplitChunksPlugin: [Getter],
//       UglifyJsPlugin: [Getter],
//       CommonsChunkPlugin: [Getter]
//     },
//     web: {
//       FetchCompileWasmTemplatePlugin: [Getter],
//       JsonpTemplatePlugin: [Getter]
//     },
//     webworker: { WebWorkerTemplatePlugin: [Getter] },
//     node: {
//       NodeTemplatePlugin: [Getter],
//       ReadFileCompileWasmTemplatePlugin: [Getter]
//     },
//     debug: { ProfilingPlugin: [Getter] },
//     util: { createHash: [Getter] }
//   },
//   amp: true,
//   experimental: { unstable_runtimeJS: true }
// }